source 'https://github.com/Chj1995/DXSpecs.git'
source 'https://mirrors.tuna.tsinghua.edu.cn/git/CocoaPods/Specs.git'

use_frameworks!

platform :ios, '8.0'

target 'DXCategoryKit_Example' do
  pod 'DXCategoryKit', :path => '../'
  pod 'AFNetworking'
  pod 'SDWebImage'
  pod 'Masonry'
  pod 'MBProgressHUD'
  pod 'YYKit'
  pod 'MJRefresh'


  target 'DXCategoryKit_Tests' do
    inherit! :search_paths


  end
end
